(##namespace
 ("gvm#"
  apply-loc
  apply-opnds
  bb-label-instr
  bb-branch-instr
  bb-lbl-num
  bb-precedents
  bb-lbl-num->bb
  lbl-num->bb
  bb-non-branch-instrs
  bb-non-branch-instrs-set!
  bb-put-branch!
  bb-put-non-branch!
  bbs-entry-lbl-num-set!
  bbs-new-lbl!
  close-parms
  closure-parms-loc
  closure-parms-opnds
  comment-get
  comment-put!
  copy-loc
  copy-opnd
  env.begin!
  frame-size
  frame-slots
  gvm-instr-comment
  gvm-instr-frame
  gvm-instr-type
  ifjump-opnds
  jump-opnd
  label-entry-keys
  label-entry-opts
  label-type
  make-apply
  make-bb
  make-bbs
  make-close
  make-closure-parms
  make-comment
  make-copy
  make-frame
  make-ifjump
  make-jump
  make-label-entry
  make-label-return
  make-label-simple
  make-label-simple
  make-label-task-entry
  make-label-task-return
  make-pattern
  make-proc-obj
  make-switch
  make-switch-case
  pcontext-fs
  pcontext-map
  proc-obj-c-name-set!
  proc-obj-call-pat
  proc-obj-call-pat-set!
  proc-obj-code
  proc-obj-code-set!
  proc-obj-dead-end?
  proc-obj-expand
  proc-obj-expandable?
  proc-obj-inlinable?
  proc-obj-lift-pat
  proc-obj-name
  proc-obj-name-set!
  proc-obj-primitive?
  proc-obj-primitive?-set!
  proc-obj-side-effects?
  proc-obj-simplify
  proc-obj-standard
  proc-obj-testable?
  proc-obj-type
  proc-obj-inline-set!
  proc-obj-inlinable?-set!
  proc-obj-jump-inlinable?-set!
  proc-obj-jump-inline
  proc-obj-jump-inline-set!
  proc-obj?
  purify-procs
  return-addr-reg
  switch-case-obj
  switch-case-lbl
  switch-cases
  switch-opnd
  type-name
  virtual.begin!
  virtual.dump-cfg
  virtual.dump-dg
  virtual.dump-gvm
  virtual.end!
  apply-prim
  bbs?
  bbs->code-list
  bbs-entry-lbl-num
  bbs-next-lbl-num
  closure-parms-lbl
  code-bb
  code-slots-needed
  debug-info-add!
  debug-info-generate
  frame-closed
  frame-live?
  frame-regs
  ifjump-false
  ifjump-poll?
  ifjump-test
  ifjump-true
  jump-nb-args
  jump-poll?
  jump-ret
  jump-safe?
  label-entry-closed?
  label-entry-nb-parms
  label-entry-rest?
  label-lbl-num
  make-debug-info-state
  proc-obj-inline
  proc-obj-test
  proc-obj-testable?-set!
  proc-obj-test-set!
  switch-default
  switch-poll?




  ))
