(##namespace
 ("t-univ-1#"
  ctx-imports
  ctx-inits
  ctx-rtlib-features-used
  ctx-rtlib-features-used-set!
  gvm-proc-use
  gvm-state-current-thread
  gvm-state-glo-use
  gvm-state-nargs-use
  gvm-state-pollcount-use
  gvm-state-sp-use
  gvm-state-stack-use
  make-resource-set
  resource-set-add!
  resource-set-pop
  resource-set-stack
  univ-add-module-import
  univ-array-constructor
  univ-denv-local
  univ-emit-!=
  univ-emit-&&
  univ-emit-+
  univ-emit--
  univ-emit-/
  univ-emit-<
  univ-emit-<=
  univ-emit-=
  univ-emit->
  univ-emit->=
  univ-emit->>
  univ-emit->>>
  univ-emit-alias
  univ-emit-and
  univ-emit-array-index
  univ-emit-array-length
  univ-emit-array-literal
  univ-emit-array-push!
  univ-emit-array-shrink!
  univ-emit-array-shrink-possibly-copy!
  univ-emit-assign
  univ-emit-attribute-exists?
  univ-emit-bitand
  univ-emit-bitior
  univ-emit-bitnot
  univ-emit-bitxor
  univ-emit-call-with-arg-array
  univ-emit-cast*
  univ-emit-concat
  univ-emit-copy-array-to-extensible-array
  univ-emit-downupcast*
  univ-emit-eq?
  univ-emit-expr-statement
  univ-emit-extensible-array-literal
  univ-emit-extensible-array-to-array!
  univ-emit-extensible-subarray
  univ-emit-getglo
  univ-emit-getnargs
  univ-emit-getpeps
  univ-emit-getreg
  univ-emit-getstk
  univ-emit-glo-var-primitive-set!
  univ-emit-glo-var-set!
  univ-emit-global-var
  univ-emit-if
  univ-emit-if-expr
  univ-emit-if-instanceof
  univ-emit-inc-by
  univ-emit-local-var
  univ-emit-make-array
  univ-emit-rts-method
  univ-emit-rts-class-use
  univ-emit-map
  univ-emit-move-array-to-array
  univ-emit-new-array
  univ-emit-not
  univ-emit-obj
  univ-emit-or
  univ-emit-*
  univ-emit-rts-class
  univ-emit-rts-class-use
  univ-emit-rts-field-use
  univ-emit-rts-jumpable-use
  univ-emit-rts-method
  univ-emit-rts-method-ref
  univ-emit-rts-method-use
  univ-emit-rts-method-use
  univ-emit-parens
  univ-emit-pop
  univ-emit-rts-field-use
  univ-emit-prefix
  univ-emit-prefix-class
  univ-emit-prop-index
  univ-emit-push
  univ-emit-setglo
  univ-emit-setnargs
  univ-emit-setreg
  univ-emit-subarray
  univ-emit-this-mod-jumpable
  univ-emit-cast*-jumpable
  univ-emit-tostr
  univ-emit-try-catch
  univ-emit-unalias
  univ-emit-upcast*
  univ-emit-var-declaration
  univ-emit-while
  univ-env-name-val
  univ-field-rename
  univ-fixnum-max
  univ-fixnum-min
  univ-fixnum-representation
  univ-foldr-range
  univ-glo-use
  univ-max-memoized-fixnum
  univ-mdigit-base
  univ-mdigit-base-minus-1
  univ-mdigit-width
  univ-min-memoized-fixnum
  univ-nb-arg-regs
  univ-pop-args-to-regs
  univ-pop-args-to-vars
  univ-procedure-representation
  univ-push-args
  univ-rts-field-low-level-name
  univ-rts-method-low-level-name
  univ-single-line-comment-prefix
  univ-stack-resizable?
  univ-stk-slot-from-tos
  univ-string-representation
  univ-thread-cont-slot
  univ-thread-denv-cache1-slot
  univ-thread-denv-cache2-slot
  univ-thread-denv-cache3-slot
  univ-thread-denv-slot
  univ-tostr-method-name
  univ-use-rtlib
  univ-vector-representation
  univ-flonum-representation
  ))
