(##namespace
 ("t-univ-3#"
  univ-add-class
  univ-add-field
  univ-add-init
  univ-add-method
  univ-defs-combine
  univ-defs-combine-list
  univ-emit-absent
  univ-emit-bignum?
  univ-emit-bignum-digits
  univ-emit-bool
  univ-emit-bool?
  univ-emit-boolean?
  univ-emit-boolean-box
  univ-emit-boolean-unbox
  univ-emit-call-member
  univ-emit-call-prim
  univ-emit-char?
  univ-emit-char-box-uninterned
  univ-emit-char-unbox
  univ-emit-cons
  univ-emit-cons-inline
  univ-emit-conv*
  univ-emit-dict-delete
  univ-emit-dict-get
  univ-emit-dict-get-or-null
  univ-emit-dict-key-exists?
  univ-emit-dict-length
  univ-emit-dict-set
  univ-emit-empty-dict
  univ-emit-eof
  univ-emit-f32vector-box
  univ-emit-f64vector-box
  univ-emit-field
  univ-emit-fixnum?
  univ-emit-fixnum-box
  univ-emit-fixnum-unbox
  univ-emit-float
  univ-emit-float?
  univ-emit-float-abs
  univ-emit-float-exp
  univ-emit-float-log
  univ-emit-float-math
  univ-emit-float-sqrt
  univ-emit-float-toint
  univ-emit-flonum?
  univ-emit-flonum-box
  univ-emit-flonum-box-inline
  univ-emit-flonum?-inline
  univ-emit-flonum-unbox
  univ-emit-fn-body
  univ-emit-fn-decl
  univ-emit-foreign?
  univ-emit-frame-box
  univ-emit-frame-slots
  univ-emit-frame-unbox
  univ-emit-function?
  univ-emit-function-declaration
  univ-emit-getcar
  univ-emit-getcdr
  univ-emit-host-primitive?
  univ-emit-instanceof
  univ-emit-int
  univ-emit-int?
  univ-emit-js-bigint?
  univ-emit-js-number?
  univ-emit-js-number?-inline
  univ-emit-jump
  univ-emit-keyword?
  univ-emit-keyword-box-uninterned
  univ-emit-keyword-unbox
  univ-emit-member
  univ-emit-new
  univ-emit-new*
  univ-emit-new-continuation
  univ-emit-new-foreign
  univ-emit-new-scheme
  univ-emit-null
  univ-emit-null?
  univ-emit-null-obj
  univ-emit-null-obj?
  univ-emit-pair?
  univ-emit-pair?-inline
  univ-emit-procedure?
  univ-emit-procedure-declaration
  univ-emit-ratnum?
  univ-emit-return
  univ-emit-return-call-prim
  univ-emit-return-jump
  univ-emit-s16vector-box
  univ-emit-s32vector-box
  univ-emit-s64vector-box
  univ-emit-s8vector-box
  univ-emit-scheme?
  univ-emit-str
  univ-emit-str?
  univ-emit-str-index-code
  univ-emit-string?
  univ-emit-string-box
  univ-emit-string?-inline
  univ-emit-string-ref
  univ-emit-string->str
  univ-emit-str-length
  univ-emit-str->string
  univ-emit-str-toint
  univ-emit-structure?
  univ-emit-structure-box
  univ-emit-structure-ref
  univ-emit-structure-set!
  univ-emit-substring
  univ-emit-symbol?
  univ-emit-symbol-box-uninterned
  univ-emit-symbol-unbox
  univ-emit-this
  univ-emit-type
  univ-emit-u16vector-box
  univ-emit-u32vector-box
  univ-emit-u64vector-box
  univ-emit-u8vector-box
  univ-emit-unbound1
  univ-emit-values-box
  univ-emit-vect?
  univ-emit-vect-box
  univ-emit-vector-box
  univ-emit-vector?-inline

  univ-defs-classes
  univ-defs-fields
  univ-defs-inits
  univ-defs-methods
  univ-emit-apply
  univ-emit-boolean-obj
  univ-emit-box
  univ-emit-char-obj
  univ-emit-closure-ref
  univ-emit-closure-set!
  univ-emit-cpxnum-make
  univ-emit-decl
  univ-emit-defs
  univ-emit-deleted
  univ-emit-float-fromint
  univ-emit-key
  univ-emit-keyword-obj
  univ-emit-num-of-type
  univ-emit-optional
  univ-emit-poll-or-continue
  univ-emit-ratnum-make
  univ-emit-rest
  univ-emit-return-poll
  univ-emit-string-obj
  univ-emit-symbol-obj
  univ-emit-unbound2
  univ-emit-unused
  univ-rts-type-alias
  univ-set-ctrlpt-attrib
  univ-use-ctrlpt-init?

  univ-emit-vector-length
  univ-emit-vector-ref
  univ-emit-vector-set!
  univ-emit-vect-unbox
  univ-emit-void
  univ-emit-void?
  univ-emit-void-obj
  univ-emit-void-obj?
  univ-field-param
  univ-get-ctrlpt-attrib
  univ-ident-when-special-float
  univ-jumpable-declaration-defs
  univ-jump-method-name
  univ-make-empty-defs
  univ-with-ctrlpt-attribs
  univ-throw))
