(##namespace
 ("utils#"
  compiler-error
  compiler-internal-error
  compiler-user-warning
  keep
  list->varset
  list->vect
  lset-difference
  make-stretchable-vector
  pair-up
  pos-in-list
  ptset->list
  ptset-empty?
  ptset-every?
  sort-list
  stretchable-vector-ref
  stretchable-vector-set!
  varset->list
  varset-adjoin
  varset-difference
  varset-empty
  varset-empty?
  varset-intersects?
  varset-member?
  varset-remove
  varset-singleton
  varset-size
  varset-union
  varset-union-multi
  with-exception-handling
  map-index
  queue->list
  base92-encode
  compiler-user-error
  queue-empty
  queue-empty?
  queue-get!
  queue-put!
  stretchable-vector-length
  stretchable-vector->list
  ))
